title: Marcus Dunbar
description: Marcus Dunbar's Personal Website
baseurl: ""

username: Marcus Dunbar
typing_text: Data Nerd/Data Scientist

email: marcus.d.dunbar8@gmail.com
linkedin_username: marcus-dunbar-459b40211
github_username: marcusdjr

show_aboutme_card: false
about_me_title: About Me
about_me_description: <empty>

show_skills_card: true
skills_title: Skills

show_timeline_card: true
timeline_title: Education & Experience
cv_download_link: https://drive.google.com/file/d/1FIaJurk47rssevQnd8vDaUcCs6hC8oRK/view

show_projects_card: true
show_projects: false
projects_title: Work Projects
show_os_projects: true
os_projects_title: Portfolio Projects

show_contact_card: true
contact_title: Contacts
contact_description: Feel free to contact me wherever is comfortable for you

repository: marcusdjr/marcusdjr.github.io
github_pages:
  - sorting_algos
  - character_encoder
  - marcusdjr.github.io
  
projects:
  sort_by: stars
  exclude:
    archived: true
    forks: true
    projects:
      - marcusdjr

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
