name: Weekly deploy

on:
  schedule:
   - cron: '0 0 * * 0'
jobs:
  curl:
    runs-on: windows-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: "-X POST -H 'Authorization: token ${{ secrets.PAGES_ACCESS_TOKEN }}' -H 'Accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/marcusdjr/marcusdjr.github.io/pages/builds"
        
